#pragma unmanaged

const char * CandleStickPatternNames[64][2] = 
{
    {"None",""},
    {"Hammer","HMM"},
    {"Hanging Man","HNM"},
    {"Bullish Engulfing","UEN"},
    {"Bearish Engulfing","DEN"},
    {"Dark-cloud Cover","DCC"},
    {"Piercing Line","PEL"},
    {"Morning Star","MST"},
    {"Evening Star","EST"},
    {"Morning Doji Star","MDS"},
    {"Evening Doji Star","EDS"},
    {"Bullish Abandoned Baby","UAB"},
    {"Bearish Abandoned Baby","DAB"},
    {"Shooting Star","SHS"},
    {"Inverted Hammer","IHM"},
    {"Bearish Harami","DHA"},
    {"Bullish Harami","UHA"},
    {"Bearish Harami Cross","DHC"},
    {"Bullish Harami Cross","UHC"},
    {"Tweezer Top","TWT"},
    {"Tweezer Bottom","TWB"},
    {"Bearish Belt-Hold Line","DBH"},
    {"Bullish Belt-Hold Line","UBH"},
    {"Upside-Gap Two Crows","TCR"},
    {"Three Black Crows","TBC"},
    {"Bearish Counterattack Line","DCL"},
    {"Bullish Counterattack Line","UCL"},
    {"Three Inside Up","TIU"},
    {"Three Outside Up","TOU"},
    {"Three Inside Down","TID"},
    {"Three Outside Down","TOD"},
    {"Kicker","UKI"},
    {"Kicking","DKI"},
    {"Three White Soldiers","TWS"},
    {"Advance Block","ABL"},
    {"Deliberation","DEL"},
    {"Bearish Tri Star","DTS"},
    {"Bullish Tri Star","UTS"},
    {"Unique Three River Bottom","TRB"},		 
    {"Bearish Doji Star","DDS"},
    {"Bullish Doji Star","UDS"},
    {"Bearish Dragonfly Doji","DDD"},
    {"Bullish Dragonfly Doji","UDD"},
    {"Bearish Gravestone Doji","DGD"},
    {"Bullish Gravestone Doji","UGD"},
    {"Bearish Long Legged Doji","DLD"},
    {"Bullish Long Legged Doji","ULD"},
    {"Bearish Side-By-Side White Lines","DWL"},
    {"Bullish Side-By-Side White Lines","UWL"},
    {"Falling Three Methods","FTM"},
    {"Rising Three Methods","RTM"},
    {"Bearish Separating Lines","DSL"},
    {"Bullish Separating Lines","USL"},
    {"Downside Tasuki Gap","DTG"},
    {"Upside Tasuki Gap","UTG"},
    {"Bearish Three-Line Strike","DTL"},
    {"Bullish Three-Line Strike","UTL"},
    {"Downside Gap Three Methods","DGM"},
    {"Upside Gap Three Methods","UGM"},
    {"On Neck","ONE"},
    {"In Neck","INE"},
    {"Bearish Thrusting","DTH"},
    {"Mat Hold","MAT"},	 
	{"Doji","DOJ"}		 
};